### PR TITLE
Add support for Go 1.16

### PR DESCRIPTION
**Pull request by ccojocar**

### CODE REVIEW

**Review by cedrickring — CHANGES_REQUESTED** [review]
Bumping the go version includes:

- [x] creating a new folder for the latest go version (in this case 1.16)
- [x] changing the default go version of the action (in the root `Dockerfile`)
- [ ] bumping the version in all Dockerfile labels

There are some `make` targets that should help you with the version bumping.

Would be nice if you could complete the last 2 remaining steps :) but thanks for the good work so far 🎉

**Comment by ccojocar** [comment]
Thanks for review @cedrickring. I completed the last two points. I suppose that you want to bump the label to next major version. Please let me know if anything else is required. I look forward to using the 1.16 version in `gosec` project. Thanks!

**Comment by cedrickring** [comment]
@ccojocar unfortunately it's only a minor version bump (1.7.0). But otherwise LGTM. 

I'll create a new release after this PR is merged.

**Comment by ccojocar** [comment]
@cedrickring I updated the version label to 1.7.0. Thanks for releasing a new version!

**Review by cedrickring — APPROVED** [review]

**Pull request merged**
